In [1]:
import numpy as np

In [2]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
print(matrix[0] * 2)
matrix[0] *= 2
print(matrix)

[0 2 4]
[[0 2 4]
 [3 4 5]
 [6 7 8]]


In [4]:
matrix[0] += matrix[1]
print(matrix)

[[3 6 9]
 [3 4 5]
 [6 7 8]]


In [13]:
matrix[[0, 1]] = matrix[[1, 0]]
print(matrix)

[[3 4 5]
 [3 6 9]
 [6 7 8]]


In [29]:
matrix[:, 1]

array([4, 6, 7])